version: '3.8'

services:
  mongo:
    image: mongo
    container_name: kaanch-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - kaanch-network

  proxy:
    build: .
    container_name: kaanch-proxy
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://admin:password@kaanch-mongo:27017
    ports:
      - "9000:9000"
    networks:
      - kaanch-network

networks:
  kaanch-network:
